# permissions for end users to view imoocpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imoocpod-viewer-role
rules:
- apiGroups:
  - batch.schwarzeni.github.com
  resources:
  - imoocpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.schwarzeni.github.com
  resources:
  - imoocpods/status
  verbs:
  - get
